### PR TITLE
Allow spaces in special comments

### PR DESCRIPTION
**Pull request by m-mujica**
//! steal-remove-start
//! steal-remove-end

That works now.

Closes https://github.com/stealjs/steal/issues/1329

### CODE REVIEW

**Comment by matthewp** [comment]
lgtm

**Comment by roemhildtg** [comment]
Found another issue @m-mujica 

In windows, often times newlines aren't using the `\n` character (I wish they were always but occasionally they're not) and this can lead to hard to figure out issues...as development code isn't getting removed in production etc...

the solution: also check for `\r` character?
```

function makeTagRegEx(tag) {
	return new RegExp(
		"(\\s?)//!(\\s?)" + tag + "-start((.|\n|\r)*?)//!(\\s?)" + tag + "-end",
		"gim"
	);
}
```

**Comment by chasenlehara** [comment]
@roemhildtg Would you mind opening a new issue for that please?

**Comment by roemhildtg** [comment]
Sure @chasenlehara sorry I was going to do that, and got sidetracked...

**Pull request merged**
