### PR TITLE
Normalization fix

### PR DESCRIPTION
**Pull request by pYr0x**
fix the problem, that module names are not normalized when using package.json as config in build process

this fix some of the problems with
stealjs/steal#578

### CODE REVIEW

**Comment by matthewp** [comment]
Can you provide a test? Might enlighten why the tests are failing. Here's an existing multiple main test: https://github.com/stealjs/steal-tools/blob/master/test/multibuild_test.js#L1081

Could use that to base your test off of.

**Comment by matthewp** [comment]
@pYr0x I think this is not needed anymore, right?

**Comment by pYr0x** [comment]
i have to check if a multi main with npm package is working...

somethink like this
```
var stealTools = require("steal-tools");

var promise = stealTools.build({
  main: ["myproject/main", "myproject/login"],
  config: __dirname+"/package.json!npm"
},{
  bundleSteal: true,
  minify: true,
  debug: false,
  quiet: false
});
```

**Comment by matthewp** [comment]
Oh, I thought you had added a test like that. Ok, let me know.

**Comment by pYr0x** [comment]
multi-main now works in minor 
still have some problems, but not with the normalization so close this

**Pull request closed without merging**
