### PR TITLE
Get steal-tools to output slim format

### PR DESCRIPTION
**Pull request by m-mujica**

### CODE REVIEW

**Comment by m-mujica** [comment]
@matthewp had to make more changes to transpile in order to get working the CJS example

Building an app with the following modules: 

```js
// main.js
var foo = require("./foo");
window.foo = foo;
```

```js
// foo.js
module.exports = "foo"
```

Generates the following output:

```js
/*[slim-loader]*/
(function(modules) {
	var cache = {};

	function stealRequire(moduleId) {
		if (cache[moduleId]) {
			return cache[moduleId];
		}

		var mod = (cache[moduleId] = {
			exports: {}
		});

		modules[moduleId].call(mod.exports, stealRequire, mod.exports, mod);
		return mod.exports;
	}

	// import the main module
	stealRequire(0);
})([
	function f(stealRequire, stealExports, stealModule) {
		stealModule.exports = "foo";
	},
	function f(stealRequire, stealExports, stealModule) {
		var foo = stealRequire("./foo");
		window.foo = foo;
	}
]);
```
 
The only thing missing to get it to work is the module id replacement in the output, the plan is to take care of that tomorrow and get to work on plugins next week.

**Comment by m-mujica** [comment]
@matthewp got the simple example working! with the array format we discussed, the final bundle looks like this: 

```js
/*[slim-loader]*/
(function(modules) {
  var cache = {};

  var modulesMap = {};
  modules.forEach(function(m) {
    modulesMap[m[0]] = m[1];
  });

  function stealRequire(moduleId) {
    if (cache[moduleId]) {
      return cache[moduleId];
    }

    var stealModule = (cache[moduleId] = {
      exports: {}
    });

    modulesMap[moduleId].call(
      stealModule.exports,
      stealRequire,
      stealModule.exports,
      stealModule
    );

    return stealModule.exports;
  }

  // import the main module
  stealRequire(2);
})([
  [
    3,
    function(stealRequire, stealExports, stealModule) {
      stealModule.exports = "foo";
    }
  ],
  [
    2,
    function(stealRequire, stealExports, stealModule) {
      var foo = stealRequire(3);
      window.foo = foo;
    }
  ]
]);
```

giphy

Still need to work on the progressive app tho 😓

**Comment by matthewp** [comment]
Nice!

**Comment by m-mujica** [comment]
@matthewp finally got the progressive/async example built with steal-tools 

mrw-i-finally-got-the-promotion-and-raise-i-had-been-working-towards-for-several-months-5225

**Comment by matthewp** [comment]
👍 merge away

**Pull request merged**
