### PR TITLE
Minify JS bundles

### PR DESCRIPTION
**Pull request by m-mujica**

### CODE REVIEW

**Comment by m-mujica** [comment]
`graph/minify` (the module that minifies nodes) is used in the following modules:

lib/build/transform.js
lib/bundle/add_global_shim.js
lib/bundle/add_traceur_runtime.js
lib/graph/make_ordered_transpiled_minified_graph.js
lib/stream/build.js
lib/stream/minify.js

It seems that both modules below deal with singles nodes, so we should keep using `graph/minify`.

lib/bundle/add_global_shim.js
lib/bundle/add_traceur_runtime.js

What about 

lib/build/transform.js
lib/graph/make_ordered_transpiled_minified_graph.js
lib/stream/build.js
lib/stream/minify.js

I'm guessing stream/build should also minify bundles, what do you think @matthewp?

**Comment by matthewp** [comment]
Sounds good to me.

**Comment by matthewp** [comment]
@justinbmeyer I was told that you had some concerns about this change, can you explain those in this issue?

**Comment by m-mujica** [comment]
@matthewp it was about not minifying the nodes before the bundle algorithm does its magic.... Nodes with lots of comments and little code might introduce noise to the algorithm results.... If I got it correctly // @justinbmeyer

**Comment by matthewp** [comment]
Ok, @m-mujica could you do some measurements of bundle sizes with and without this change? Would be curious to see an app like place-my-order and see how bundle sizes are affected if you do minification at the node vs. bundle level.

**Comment by m-mujica** [comment]
PMO bundles - with the current individual node minification 

```
total 448
-rw-r--r--  1 mmujica  staff  147521  3 May 14:23 history-componen-51b0674a.js
-rw-r--r--  1 mmujica  staff   77823  3 May 14:23 history-component-new.js
drwxr-xr-x  8 mmujica  staff     272  3 May 14:23 place-my-order

dist/bundles/place-my-order:
total 608
-rw-r--r--  1 mmujica  staff      50  3 May 14:23 home.css
-rw-r--r--  1 mmujica  staff    3318  3 May 14:23 home.js
-rw-r--r--  1 mmujica  staff   67850  3 May 14:23 index.css
-rw-r--r--  1 mmujica  staff  231786  3 May 14:23 index.js
drwxr-xr-x  4 mmujica  staff     136  3 May 14:23 order
drwxr-xr-x  4 mmujica  staff     136  3 May 14:23 restaurant

dist/bundles/place-my-order/order:
total 32
-rw-r--r--  1 mmujica  staff  14780  3 May 14:23 history.js
drwxr-xr-x  4 mmujica  staff    136  3 May 14:23 new

dist/bundles/place-my-order/order/new:
total 88
-rw-r--r--  1 mmujica  staff     28  3 May 14:23 new.css
-rw-r--r--  1 mmujica  staff  39123  3 May 14:23 new.js

dist/bundles/place-my-order/restaurant:
total 16
-rw-r--r--  1 mmujica  staff  7288  3 May 14:23 details.js
drwxr-xr-x  4 mmujica  staff   136  3 May 14:23 list

dist/bundles/place-my-order/restaurant/list:
total 32
-rw-r--r--  1 mmujica  staff     34  3 May 14:23 list.css
-rw-r--r--  1 mmujica  staff  11879  3 May 14:23 list.js
```

**Comment by m-mujica** [comment]
PMO bundles - minifying at the bundle level 

```
total 440
-rw-r--r--  1 mmujica  staff   142K  3 May 14:30 history-componen-51b0674a.js
-rw-r--r--  1 mmujica  staff    76K  3 May 14:30 history-component-new.js
drwxr-xr-x  8 mmujica  staff   272B  3 May 14:30 place-my-order

dist/bundles/place-my-order:
total 600
-rw-r--r--  1 mmujica  staff    50B  3 May 14:30 home.css
-rw-r--r--  1 mmujica  staff   3.1K  3 May 14:30 home.js
-rw-r--r--  1 mmujica  staff    66K  3 May 14:30 index.css
-rw-r--r--  1 mmujica  staff   221K  3 May 14:30 index.js
drwxr-xr-x  4 mmujica  staff   136B  3 May 14:30 order
drwxr-xr-x  4 mmujica  staff   136B  3 May 14:30 restaurant

dist/bundles/place-my-order/order:
total 32
-rw-r--r--  1 mmujica  staff    14K  3 May 14:30 history.js
drwxr-xr-x  4 mmujica  staff   136B  3 May 14:30 new

dist/bundles/place-my-order/order/new:
total 88
-rw-r--r--  1 mmujica  staff    28B  3 May 14:30 new.css
-rw-r--r--  1 mmujica  staff    38K  3 May 14:30 new.js

dist/bundles/place-my-order/restaurant:
total 16
-rw-r--r--  1 mmujica  staff   6.9K  3 May 14:30 details.js
drwxr-xr-x  4 mmujica  staff   136B  3 May 14:30 list

dist/bundles/place-my-order/restaurant/list:
total 32
-rw-r--r--  1 mmujica  staff    34B  3 May 14:30 list.css
-rw-r--r--  1 mmujica  staff    11K  3 May 14:30 list.js
```

**Comment by m-mujica** [comment]
There is no difference, at least in this app when minifying both at the node level and at the bundle level. 

|   | NODES | BUNDLE | BOTH |
|  ------ | ------: | ------: | ------: |
|  dist/bundles |  |  |  |
|  history-componen-51b0674a.js | 144K | 142K | 142K |
|  history-component-new.js | 76K | 76K | 76K |
|  place-my-order | 272B | 272B | 272B |
|   |  |  |  |
|  dist/bundles/place-my-order |  |  |  |
|  home.css | 50B | 50B | 50B |
|  home.js | 3.2K | 3.1K | 3.1K |
|  index.css | 66K | 66K | 66K |
|  index.js | 226K | 221K | 221K |
|  order | 136B | 136B | 136B |
|  restaurant | 136B | 136B | 136B |
|   |  |  |  |
|  dist/bundles/place-my-order/order |  |  |  |
|  history.js | 14K | 14K | 14K |
|  new | 136B | 136B | 136B |
|   |  |  |  |
|  dist/bundles/place-my-order/order/new: |  |  |  |
|  new.css | 28B | 28B | 28B |
|  new.js | 38K | 38K | 38K |
|   |  |  |  |
|  dist/bundles/place-my-order/restaurant |  |  |  |
|  details.js | 7.1K | 6.9K | 6.9K |
|  list | 136B | 136B | 136B |
|   |  |  |  |
|  dist/bundles/place-my-order/restaurant/list |  |  |  |
|  list.css | 34B | 34B | 34B |
|  list.js | 12K | 11K | 11K |

**Comment by m-mujica** [comment]
The final solution keeps the logic to minify individual nodes so the bundling algorithm results are not affects by comments, spaces etc.... But the bundle is minified too, so empty lines, bundles names (comments) are removed. 

With this change, there is a reduction of 5K in PMO's `index.js` bundle..

**Comment by matthewp** [comment]
👍 LGTM

**Comment by justinbmeyer** [comment]
@matthewp my concern was that individual nodes still need to be minified for the multi-build.

@m-mujica if people are not doing progressive loading, it would be nice to avoid minifying the individual nodes.

The only other minor concern is that this might ~double the build time because we are minifying twice (which if not now, used to be the slowest part of the build).

**Pull request merged**
