### PR TITLE
update multi-main test

### PR DESCRIPTION
**Pull request by pYr0x**
update multi-main test with bundled steal and progressive loaded bundle

### CODE REVIEW

**Comment by matthewp** [comment]
appveyor is currently failing but it's unrelated to this. I'm going to look into fixing it later this week and then will update this as well.

**Comment by matthewp** [comment]
If you rebase with master the tests should all pass now.

**Comment by pYr0x** [comment]
@matthewp this also should pass. Attention: this PR is against minor branch. we also have to merge minor into master when doing a version upgrade to 0.16

**Comment by matthewp** [comment]
Yeah, we'll do a 0.16 next week I think.

**Pull request merged**
