### PR TITLE
update a package because of its dependency glob wich inhired minimatc…

### PR DESCRIPTION
**Pull request by frank-dspeed**
…h less then 3

### CODE REVIEW

**Comment by matthewp** [comment]
Looks like it breaks tests, did they change the format maybe?

**Comment by pYr0x** [comment]
`transpile`  `2´ will break even more tests :(

**Comment by frank-dspeed** [comment]
Ok Nice looks like we know now what to do till next month lol :)

**Comment by matthewp** [comment]
Try rebasing with master now. An upstream bug in steal was causing tests to break.

**Comment by frank-dspeed** [comment]
hmm i am wondering the tests are showing traceur@0.0.91 should be traceur@0.0.111

**Comment by matthewp** [comment]
@m-mujica Can you look into why upgrading traceur breaks the tests?

**Comment by m-mujica** [comment]
Closing in favor of #627

**Pull request closed without merging**
