### PR TITLE
let steal know if it is bundled

### PR DESCRIPTION
**Pull request by matthewp**
This is part of https://github.com/stealjs/steal-tools/pull/423

### CODE REVIEW

**Comment by pYr0x** [comment]
please do not forget to correct: https://github.com/stealjs/steal-tools/pull/425/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R23

**Comment by matthewp** [comment]
It is already

**Comment by matthewp** [comment]
Oh sorry, it is not.

**Comment by matthewp** [comment]
@pYr0x this was merged and published as 0.15.5 and also merged into minor if you are using that branch currently.

**Pull request merged**
