### PR TITLE
improve docs

### LINKED ISSUE #434: steal `bundle` is not a BuildOptions it is a SystemConfig
in the docs the `bundle` options is located at http://stealjs.com/docs/steal-tools.BuildOptions.html but thats not true. 
as you see in a test (https://github.com/stealjs/steal-tools/blob/minor/test/multibuild_test.js#L1789) the `bundle` options is located in the SystemConfig.
we should improve the docs

### PR DESCRIPTION
**Pull request by pYr0x**
close #434

### CODE REVIEW

**Comment by pYr0x** [comment]
dont know why it is failing by changing the docs.
@matthewp if this is ok, pls merge

**Comment by matthewp** [comment]
Did you have latest master? You are seeing an issue that's currently fixed.

**Comment by pYr0x** [comment]
> You are seeing an issue that's currently fixed.

i dont know what you mean. i only edit the markdownfiles. so there is no impact on the js files

**Comment by matthewp** [comment]
Yeah, but master is currently broken, so that's why your change is failing.  Change the jquery version in package.json to `"jquery": "^2.0.0",` and it should pass.  jQuery released a new version that broke our tests. It's not important to have the latest version here.

**Comment by pYr0x** [comment]
i added jquery 2.0.0 (the commit comment is wrong) and it breaks anyways. the error in in 
`✓ Creates a stream containing the dependency graph (40ms)`

**Comment by matthewp** [comment]
Going to look into what's breaking then.

**Pull request merged**
