### PR TITLE
Update Node version to 13

### LINKED ISSUE #1151: Engines field not compatible with Node 12
Steal tools breaking yarn with error:

`error steal-tools@2.2.2: The engine "node" is incompatible with this module. Expected version "4.x - 10.x". Got "12.13.1"
error Found incompatible module.`

Due to engines defined in package.json:

```
  "engines": {
    "node": "8.x - 10.x"
  },
```

### PR DESCRIPTION
**Pull request by cherifGsoul**
Closes #1151 

Update node engine field in `package.json` and `.travis.yml` to `13.x`.

### CODE REVIEW

**Comment by matthewp** [comment]
You might also need to update `mock-fs`, that might be the cause of the tests failing.

**Comment by cherifGsoul** [comment]
@matthewp Thank you, it fixed it, just for windows it can not find `C:\stealconfig.js` file.

**Comment by matthewp** [comment]
I think that's expected as part of that test. It looks like the error on Windows is something else, look at the stack trace: https://ci.appveyor.com/project/matthewp/steal-tools-427/builds/29763981

**Comment by cherifGsoul** [comment]
@matthewp What is the windows version and architecture used in `appveyor`? Firefox is not found in `appveyor` but works fine on my local image, maybe a `lauchpad` issue, the build passes with chrome.

**Comment by matthewp** [comment]
Awesome, looks good to me 👍

**Pull request merged**
