### PR TITLE
Create configuration with bundles to be loaded

### LINKED ISSUE #541: Create configuration that specifies what bundles are needed to load
If you provide steal-tools something like:

```js
stealTools.build({
  bundle: [
    "home",
    "register",
    "product"
  ]
});
```

This could result in shared bundles being created. Ideally you want to prevent a waterfall scenario, which you could do by listing the scripts in your html:

```js
<script src="/dist/bundles/app/main.js" defer></script>
<script src="/dist/bundles/app/home.js" defer></script>
<script src="/dist/bundles/app/home-register.js" defer></script>
<script src="/dist/bundles/app/home-register-product.js" defer></script>
```

The browser will fetch all of these scripts in parallel so there is no waterfall.

The **_problem_** is that a user doesn't know what script tags they need to add. What I am proposing is that we write out this information somewhere that you can use in your server-side templating. 

One idea I had (not necessarily the best) is to write a json file into your dest, maybe `dist/bundles.json` that looks like:

```json
{
  "bundles/app/home": {
    "main": "bundles/app/main",
    "shared": [
      "bundles/app/home-register",
      "bundles/app/home-register-product"
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by m-mujica**
Closes #541

@matthewp this code will write the following manifest for PMO 

if you'd use this file to write out script tag to preload stuff, you'd 

a) use the key as the script src if `shared.length` is 0
b) use the bundle name in `shared[0]` when it's the only one
c) load any of the bundles in `shared` when multiple are available

is this what you had in mind? 

```json
{
    "bundles/history-componen-51b0674a": {
        "shared": []
    },
    "bundles/history-component-new": {
        "shared": []
    },
    "bundles/place-my-order/home": {
        "shared": []
    },
    "bundles/place-my-order/home.css!": {
        "shared": []
    },
    "bundles/place-my-order/index": {
        "shared": []
    },
    "bundles/place-my-order/index.css!": {
        "shared": []
    },
    "bundles/place-my-order/order/history": {
        "shared": []
    },
    "bundles/place-my-order/order/new/new": {
        "shared": []
    },
    "bundles/place-my-order/order/new/new.css!": {
        "shared": []
    },
    "bundles/place-my-order/restaurant/details": {
        "shared": []
    },
    "bundles/place-my-order/restaurant/list/list": {
        "shared": []
    },
    "bundles/place-my-order/restaurant/list/list.css!": {
        "shared": []
    },
    "place-my-order@0.10.0#home.component!done-component@0.6.0-pre.5#component": {
        "shared": [
            "bundles/place-my-order/home"
        ]
    },
    "place-my-order@0.10.0#index.stache!done-autorender@1.0.0#src/autorender": {
        "shared": [
            "bundles/place-my-order/index"
        ]
    },
    "place-my-order@0.10.0#order/history.component!done-component@0.6.0-pre.5#component": {
        "shared": [
            "bundles/history-componen-51b0674a",
            "bundles/history-component-new",
            "bundles/place-my-order/order/history"
        ]
    },
    "place-my-order@0.10.0#order/new/new": {
        "shared": [
            "bundles/history-componen-51b0674a",
            "bundles/history-component-new",
            "bundles/place-my-order/order/new/new"
        ]
    },
    "place-my-order@0.10.0#restaurant/details.component!done-component@0.6.0-pre.5#component": {
        "shared": [
            "bundles/history-componen-51b0674a",
            "bundles/place-my-order/restaurant/details"
        ]
    },
    "place-my-order@0.10.0#restaurant/list/list": {
        "shared": [
            "bundles/history-componen-51b0674a",
            "bundles/place-my-order/restaurant/list/list"
        ]
    }
}
```

### CODE REVIEW

**Comment by m-mujica** [comment]
A smaller example from one of the tests:

```json
{
	"bundles/app/main": {
		"shared": []
	},
	"app@1.0.0#main": {
		"shared": [
			"bundles/app/main"
		]
	},
	"bundles/bundleA": {
		"shared": []
	},
	"bundleA": {
		"shared": [
			"bundles/bundleA"
		]
	},
	"bundles/bundleB": {
		"shared": []
	},
	"bundleB": {
		"shared": [
			"bundles/bundleB"
		]
	}
}
```

**Comment by matthewp** [comment]
Hey @m-mujica. Thinking about it more I'd make 3 changes:

1. Only list the top-level bundles (those things that are in `loader.bundle`) in the root object.
2. Since "shared" is the only key I think the top-level bundle names should be an array, skip the extra property.
3. Make the shared bundles values be a path from baseURL.  So for example `dist/bundles/history-componen-51b0674a.js` instead of the bundle name.  This will make it easier both for humans and automated tooling (like what we might build into done-ssr) to consume these.

**Comment by m-mujica** [comment]
- [ ] Only list the top-level bundles in the root object
- [ ] Skip the `shared` property
- [ ] Use relative bundles path inside the array of "shared" bundles

**Comment by m-mujica** [comment]
>1. Only list the top-level bundles (those things that are in loader.bundle) in the root object.

@matthewp the issue I see with this is that the manifest won't include any info about the css bundles, see the updated output from PMO:

```json
{
    "place-my-order@0.10.0#home.component!done-component@0.6.0-pre.5#component": [
        "dist/bundles/place-my-order/home.js"
    ],
    "place-my-order@0.10.0#order/history.component!done-component@0.6.0-pre.5#component": [
        "dist/bundles/history-componen-51b0674a.js",
        "dist/bundles/history-component-new.js",
        "dist/bundles/place-my-order/order/history.js"
    ],
    "place-my-order@0.10.0#order/new/new": [
        "dist/bundles/history-componen-51b0674a.js",
        "dist/bundles/history-component-new.js",
        "dist/bundles/place-my-order/order/new/new.js"
    ],
    "place-my-order@0.10.0#restaurant/details.component!done-component@0.6.0-pre.5#component": [
        "dist/bundles/history-componen-51b0674a.js",
        "dist/bundles/place-my-order/restaurant/details.js"
    ],
    "place-my-order@0.10.0#restaurant/list/list": [
        "dist/bundles/history-componen-51b0674a.js",
        "dist/bundles/place-my-order/restaurant/list/list.js"
    ]
}
```

Also, I have logic to filter out the css bundles from the "shared" array since it does not make sense to me, if I comment out that condition you'd get the follow json instead.

```json
```

**Comment by matthewp** [comment]
@m-mujica what was your thinking as far as excluding CSS? Why do you think it's not useful?

**Comment by m-mujica** [comment]
@matthewp I made the changes as we discussed. The logic to compute weight is very simple but we can change that later. The example below is PMO's manifest.

```json
{
    "place-my-order@0.10.0#home.component!done-component@0.6.0-pre.5#component": {
        "dist/bundles/place-my-order/home.css": {
            "type": "style",
            "weight": 1
        },
        "dist/bundles/place-my-order/home.js": {
            "type": "script",
            "weight": 2
        }
    },
    "place-my-order@0.10.0#index.stache!done-autorender@1.0.0#src/autorender": {
        "dist/bundles/place-my-order/index.css": {
            "type": "style",
            "weight": 1
        },
        "dist/bundles/place-my-order/index.js": {
            "type": "script",
            "weight": 2
        }
    },
    "place-my-order@0.10.0#order/history.component!done-component@0.6.0-pre.5#component": {
        "dist/bundles/history-componen-51b0674a.js": {
            "type": "script",
            "weight": 3
        },
        "dist/bundles/history-component-new.js": {
            "type": "script",
            "weight": 3
        },
        "dist/bundles/place-my-order/order/history.js": {
            "type": "script",
            "weight": 2
        }
    },
    "place-my-order@0.10.0#order/new/new": {
        "dist/bundles/history-componen-51b0674a.js": {
            "type": "script",
            "weight": 3
        },
        "dist/bundles/history-component-new.js": {
            "type": "script",
            "weight": 3
        },
        "dist/bundles/place-my-order/order/new/new.css": {
            "type": "style",
            "weight": 1
        },
        "dist/bundles/place-my-order/order/new/new.js": {
            "type": "script",
            "weight": 2
        }
    },
    "place-my-order@0.10.0#restaurant/details.component!done-component@0.6.0-pre.5#component": {
        "dist/bundles/history-componen-51b0674a.js": {
            "type": "script",
            "weight": 3
        },
        "dist/bundles/place-my-order/restaurant/details.js": {
            "type": "script",
            "weight": 2
        }
    },
    "place-my-order@0.10.0#restaurant/list/list": {
        "dist/bundles/history-componen-51b0674a.js": {
            "type": "script",
            "weight": 3
        },
        "dist/bundles/place-my-order/restaurant/list/list.css": {
            "type": "style",
            "weight": 1
        },
        "dist/bundles/place-my-order/restaurant/list/list.js": {
            "type": "script",
            "weight": 2
        }
    }
}
```

**Comment by matthewp** [comment]
Awesome 👍  Think this looks really good.

**Pull request merged**
