### PR TITLE
Better minify error messaging

### PR DESCRIPTION
**Pull request by whitecolor**
https://github.com/stealjs/steal-tools/issues/357

### CODE REVIEW

**Comment by matthewp** [comment]
Can you fix the lint errors (missing semicolon)?  Then I'll merge.

**Comment by whitecolor** [comment]
done

**Comment by matthewp** [comment]
Still missing a couple as shown here:  https://travis-ci.org/stealjs/steal-tools/jobs/105163957

You can see this locally by running `grunt jshint`.

**Comment by whitecolor** [comment]
Ok, sorry my carelessness

**Pull request merged**
