### PR TITLE
live reload throw an error while building

### PR DESCRIPTION
**Pull request by pYr0x**
close https://github.com/stealjs/steal-tools/issues/431

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks, i'm fixing windows ci now.

**Comment by matthewp** [comment]
If you rebase with master the tests should all pass now.

**Comment by pYr0x** [comment]
That took some doing... @matthewp dont know why coveralls fails, i added 2 tests

**Comment by matthewp** [comment]
I've changed the threshold to -2%.

**Pull request merged**
