### PR TITLE
Add file size benchmarks

### LINKED ISSUE #664: Create file size benchmarks for common scenarios
The scenarios of the slim loader usage is:

1. A single bundle (see [this example](https://github.com/matthewp/webpack-research/tree/master/single)).
2. Multiple bundles, progressively loaded (see [this example](https://github.com/matthewp/webpack-research/tree/master/split)).
3. Single or multiple bundles using a plugin (there are no runtime plugins in webpack).

We should create some tests that have a basic example of each of these. The test will compare the size of a generated build to that of a snapshot. 

This way we can prevent accidental feature-creep affecting file size. That's not to say we won't ever increase the size of the shim, but when we do it will break a test and we'll have to explicitly make the decision to create a new snapshot.

### PR DESCRIPTION
**Pull request by m-mujica**
Closes #664

screen shot 2017-06-30 at 17 17 38

screen shot 2017-06-30 at 17 16 54

### CODE REVIEW

**Comment by m-mujica** [comment]
@matthewp is this what you had in mind?

**Comment by matthewp** [comment]
Yeah, looks good. Windows failing is probably a path issue, right?

**Comment by matthewp** [comment]
We just need to remember to add a snapshot test for each new add-on we make.

Do you want to try and reduce the size here or in another issue?

**Comment by m-mujica** [comment]
@matthewp yeah, different issue sounds good. I'll create the issue and work on it. 

Interesting the window bundles are bigger than the ones in MacOS, I guess b/c the module identifier in the config are different, should I add some kind of offset to the comparation? The biggest different seems to be 3b

**Comment by m-mujica** [comment]
https://ci.appveyor.com/project/matthewp/steal-tools-427/build/1.0.1337#L1296

**Comment by m-mujica** [comment]
The `offset` thing is not very elegant, but it did the trick. Thoughts?

**Comment by matthewp** [comment]
Good enough I guess :shrug:

**Pull request merged**
